/**
 * Days 21-30: the hard tier.
 *
 * Same ten settings again, at the top of the ladder: the student has to give
 * reasons, use past and future tense, disagree politely, and hold a longer turn
 * than a single clause. Model answers are still short enough for a child to say
 * out loud in one breath - difficulty here is in the language, not the length.
 */
export default [
  {
    day: 21, location: "school", topic: "Giving a Short Talk",
    character: { id: "teacher", name: "Mrs. Sharma", role: "teacher" },
    intro: "Your teacher has asked you to speak in front of the class. Talk about something you like.",
    vocabulary: ["I would like to talk about", "first of all", "the reason is", "for example", "in conclusion"],
    turns: [
      { npc: "It is your turn to speak. What will you talk about today?" },
      { prompt: "Say what your talk is about.",
        expected: ["I would like to talk about my favourite book.", "Today I will talk about my village.", "I want to talk about my family."],
        keywords: [["talk"]], expects: "state", slot: "subject",
        hint: "Try: \"I would like to talk about my favourite book.\"" },
      { npc: "A good choice. Tell the class why you chose it." },
      { prompt: "Explain your reason for choosing it.",
        expected: ["I chose it because it is very interesting.", "The reason is that I love reading it.", "I chose this because it makes me happy."],
        keywords: [["because", "reason"]], expects: "state",
        hint: "Try: \"I chose it because it is very interesting.\"" },
      { npc: "Can you give the class an example?" },
      { prompt: "Give an example to support what you said.",
        expected: ["For example, it teaches us to be brave.", "For example, I read it every evening.", "For example, my brother liked it too."],
        keywords: [["example"]], expects: "state",
        hint: "Try: \"For example, it teaches us to be brave.\"" },
      { npc: "Very good. How did you feel when you first read it?" },
      { prompt: "Describe how you felt, using the past tense.",
        expected: ["I felt very happy when I read it.", "I was excited when I first read it.", "I felt surprised at the ending."],
        keywords: [["felt", "was"]], expects: "state",
        hint: "Try: \"I felt very happy when I read it.\"" },
      { npc: "That was a lovely talk. Well done." },
      { prompt: "Finish your talk and thank the class.",
        expected: ["In conclusion, I recommend it to everyone. Thank you.", "That is all, thank you for listening.", "Thank you all for listening to me."],
        keywords: [["thank"]], expects: "state",
        hint: "Try: \"That is all, thank you for listening.\"" }
    ]
  },

  {
    day: 22, location: "park", topic: "Making Plans with a Friend",
    character: { id: "friend", name: "Ananya", role: "friend" },
    intro: "Your friend wants to meet this Sunday. Agree on a plan together.",
    vocabulary: ["are you free", "how about", "instead", "let us meet", "see you then"],
    turns: [
      { npc: "Are you free on Sunday? I was thinking we could do something." },
      { prompt: "Say whether you are free and suggest something.",
        expected: ["Yes, I am free. How about going to the park?", "Yes, I am free on Sunday. Shall we watch a film?", "I am free. We could go cycling."],
        keywords: [["free"]], expects: "yes_no",
        hint: "Try: \"Yes, I am free. How about going to the park?\"" },
      { npc: "Hmm, I went to the park last week. Could we do something else?" },
      { prompt: "Politely suggest a different idea.",
        expected: ["How about the library instead?", "We could go swimming instead.", "Then let us visit the market instead."],
        keywords: [["instead", "could", "how"]], expects: "state", slot: "idea",
        hint: "Try: \"How about the library instead?\"" },
      { npc: "That sounds much better! What time shall we meet?" },
      { prompt: "Suggest a time to meet.",
        expected: ["Let us meet at four o'clock.", "How about ten in the morning?", "Shall we meet at three?"],
        keywords: [["meet"]], expects: "time", slot: "time",
        hint: "Try: \"Let us meet at four o'clock.\"" },
      { npc: "Four is a little late for me. Could we make it earlier?" },
      { prompt: "Agree politely and suggest an earlier time.",
        expected: ["Of course, let us meet at two.", "That is fine, how about two o'clock?", "No problem, we can meet earlier."],
        keywords: [["earlier", "two", "fine", "course"]], expects: "state",
        hint: "Try: \"Of course, let us meet at two.\"" },
      { npc: "Perfect. I will wait for you near the gate." },
      { prompt: "Confirm the plan and say goodbye.",
        expected: ["See you on Sunday then.", "Great, see you then.", "All right, see you at two."],
        keywords: [["see"]], expects: "state",
        hint: "Try: \"See you on Sunday then.\"" }
    ]
  },

  {
    day: 23, location: "shop", topic: "Returning Something",
    character: { id: "shopkeeper", name: "Mr. Verma", role: "shopkeeper" },
    intro: "The bag you bought yesterday is torn. Ask the shopkeeper to change it.",
    vocabulary: ["I bought this", "it is torn", "could you change it", "receipt", "yesterday"],
    turns: [
      { npc: "Good morning. Is there a problem?" },
      { prompt: "Explain that you bought this here yesterday.",
        expected: ["I bought this bag here yesterday.", "I bought this from your shop yesterday.", "Yesterday I bought this bag here."],
        keywords: [["bought", "yesterday"]], expects: "state",
        hint: "Try: \"I bought this bag here yesterday.\"" },
      { npc: "I see. What is wrong with it?" },
      { prompt: "Explain what is wrong with it.",
        expected: ["It is torn near the handle.", "The zip is broken.", "It is torn already."],
        keywords: [["torn", "broken"]], expects: "state", slot: "problem",
        hint: "Try: \"It is torn near the handle.\"" },
      { npc: "That should not happen. Do you have the receipt?" },
      { prompt: "Say whether you have the receipt.",
        expected: ["Yes, here is the receipt.", "Yes, I have the receipt with me.", "No, I do not have the receipt."],
        keywords: [["receipt"]], expects: "yes_no",
        hint: "Try: \"Yes, here is the receipt.\"" },
      { npc: "Thank you. Would you like your money back, or another bag?" },
      { prompt: "Say what you would prefer.",
        expected: ["I would prefer another bag.", "Could you change it for another one?", "I would like my money back, please."],
        keywords: [["prefer", "another", "money"]], expects: "state",
        hint: "Try: \"I would prefer another bag.\"" },
      { npc: "Of course. I am sorry for the trouble." },
      { prompt: "Accept the apology politely.",
        expected: ["That is all right, thank you.", "No problem, thank you for helping.", "It is fine, thank you."],
        keywords: [["thank", "right", "fine", "problem"]], expects: "state",
        hint: "Try: \"That is all right, thank you.\"" }
    ]
  },

  {
    day: 24, location: "restaurant", topic: "A Problem with the Order",
    character: { id: "waiter", name: "Sanjay", role: "waiter" },
    intro: "The food that arrived is not what you ordered. Explain politely.",
    vocabulary: ["excuse me", "I ordered", "this is not", "could you check", "no problem"],
    turns: [
      { npc: "Here is your food. Please enjoy your meal." },
      { prompt: "Politely say this is not what you ordered.",
        expected: ["Excuse me, this is not what I ordered.", "Sorry, I think this is not my order.", "Excuse me, I did not order this."],
        keywords: [["ordered", "order"]], expects: "state",
        hint: "Try: \"Excuse me, this is not what I ordered.\"" },
      { npc: "Oh! I am very sorry. What did you order?" },
      { prompt: "Say what you actually ordered.",
        expected: ["I ordered rice and dal.", "I asked for vegetable rice.", "My order was rice and dal."],
        keywords: [["ordered", "order", "asked"]], expects: "state", slot: "food",
        hint: "Try: \"I ordered rice and dal.\"" },
      { npc: "Let me check with the kitchen. It will take ten minutes." },
      { prompt: "Ask whether it can be done faster, politely.",
        expected: ["Could you make it a little faster, please?", "Is it possible to be quicker?", "Could it come sooner, please?"],
        keywords: [["faster", "quicker", "sooner"]], expects: "question",
        hint: "Try: \"Could you make it a little faster, please?\"" },
      { npc: "I will ask the cook to hurry. Would you like some water while you wait?" },
      { prompt: "Accept politely.",
        expected: ["Yes, please. Thank you.", "Yes, some water would be nice.", "That would be very kind, thank you."],
        keywords: [["yes", "thank", "please"]], expects: "yes_no",
        hint: "Try: \"Yes, please. Thank you.\"" },
      { npc: "Here is your correct order. Again, I am sorry for the mistake." },
      { prompt: "Say it is fine and thank him.",
        expected: ["It is fine, thank you.", "No problem, thank you for fixing it.", "That is all right, thank you."],
        keywords: [["thank", "fine", "problem", "right"]], expects: "state",
        hint: "Try: \"It is fine, thank you.\"" }
    ]
  },

  {
    day: 25, location: "city", topic: "Reporting a Lost Bag",
    character: { id: "stranger", name: "Officer Rao", role: "police" },
    intro: "You have lost your bag in the city. Report it to the police officer.",
    vocabulary: ["I have lost", "it looks like", "it happened", "inside there was", "phone number"],
    turns: [
      { npc: "You look upset. What has happened?" },
      { prompt: "Explain that you have lost your bag.",
        expected: ["I have lost my bag.", "I lost my bag somewhere.", "My bag is missing."],
        keywords: [["lost", "missing"]], expects: "state",
        hint: "Try: \"I have lost my bag.\"" },
      { npc: "I am sorry to hear that. What does it look like?" },
      { prompt: "Describe the bag.",
        expected: ["It is a small blue bag.", "It is a black school bag.", "It is brown with a long strap."],
        keywords: [["bag"]], expects: "state", slot: "description",
        hint: "Try: \"It is a small blue bag.\"" },
      { npc: "Where do you think you lost it?" },
      { prompt: "Say where you think you lost it, using the past tense.",
        expected: ["I think I left it on the bus.", "I lost it near the market.", "I left it at the shop."],
        keywords: [["left", "lost"]], expects: "place", slot: "place",
        hint: "Try: \"I think I left it on the bus.\"" },
      { npc: "What was inside the bag?" },
      { prompt: "Say what was inside it.",
        expected: ["My books and my water bottle were inside.", "There were some books inside.", "Inside there was my lunch box."],
        keywords: [["inside", "books", "were"]], expects: "state", slot: "contents",
        hint: "Try: \"My books and my water bottle were inside.\"" },
      { npc: "I have written it down. We will call you if we find it." },
      { prompt: "Thank the officer and give your phone number.",
        expected: ["Thank you. My number is nine eight seven six.", "Thank you, sir. Here is my phone number.", "Thank you very much for your help."],
        keywords: [["thank"]], expects: "state",
        hint: "Try: \"Thank you, sir. Here is my phone number.\"" }
    ]
  },

  {
    day: 26, location: "home", topic: "Talking About Your Future",
    character: { id: "mother", name: "Mummy", role: "mother" },
    intro: "Your mother asks what you want to be when you grow up. Explain your dream.",
    vocabulary: ["when I grow up", "I want to become", "so that", "I am good at", "I hope"],
    turns: [
      { npc: "You are growing up so fast. What do you want to be one day?" },
      { prompt: "Say what you want to become.",
        expected: ["I want to become a doctor.", "When I grow up I want to be a teacher.", "I would like to become an engineer."],
        keywords: [["want", "become", "be"]], expects: "state", slot: "job",
        hint: "Try: \"I want to become a doctor.\"" },
      { npc: "That is a wonderful dream. Why that one?" },
      { prompt: "Give your reason.",
        expected: ["Because I want to help sick people.", "Because I like teaching children.", "Because I am good at science."],
        keywords: [["because"]], expects: "state",
        hint: "Try: \"Because I want to help sick people.\"" },
      { npc: "And what must you do to reach that dream?" },
      { prompt: "Say what you will have to do.",
        expected: ["I will have to study hard.", "I must study science every day.", "I will work hard at school."],
        keywords: [["study", "work", "hard"]], expects: "state",
        hint: "Try: \"I will have to study hard.\"" },
      { npc: "That is true. Which subject will help you most?" },
      { prompt: "Name the subject and say why it helps.",
        expected: ["Science, because doctors need it.", "Maths will help me the most.", "English, because I must talk to people."],
        keywords: [["science", "maths", "english"]], expects: "state", slot: "subject",
        hint: "Try: \"Science, because doctors need it.\"" },
      { npc: "I am proud of you. I know you will do well." },
      { prompt: "Thank your mother and say you will try.",
        expected: ["Thank you, Mummy. I will try my best.", "Thank you. I hope I can do it.", "Thank you for believing in me."],
        keywords: [["thank"]], expects: "state",
        hint: "Try: \"Thank you, Mummy. I will try my best.\"" }
    ]
  },

  {
    day: 27, location: "home", topic: "A Phone Call from a Relative",
    character: { id: "mother", name: "Mummy", role: "mother" },
    intro: "Your aunt has called. Speak with her politely on the phone.",
    vocabulary: ["hello", "how are you", "speaking", "may I ask", "give my love"],
    turns: [
      { npc: "The phone is ringing. It is your aunt. Please answer it." },
      { prompt: "Answer the phone politely.",
        expected: ["Hello, this is Arjun speaking.", "Hello, good evening aunty.", "Hello, how are you aunty?"],
        keywords: [["hello"]], expects: "state",
        hint: "Try: \"Hello, this is Arjun speaking.\"" },
      { npc: "She asks how your studies are going." },
      { prompt: "Tell her how your studies are going.",
        expected: ["My studies are going well.", "They are going well, thank you.", "I am doing well in my studies."],
        keywords: [["studies", "well"]], expects: "state",
        hint: "Try: \"My studies are going well, thank you.\"" },
      { npc: "Now she is asking whether you will visit in the holidays." },
      { prompt: "Answer about the holidays, using the future.",
        expected: ["Yes, I will visit in the holidays.", "I will come next month.", "Yes, we will visit you soon."],
        keywords: [["will"]], expects: "yes_no",
        hint: "Try: \"Yes, I will visit in the holidays.\"" },
      { npc: "Ask her something too. It is polite." },
      { prompt: "Ask your aunt a polite question.",
        expected: ["How is everyone at home?", "How are you keeping, aunty?", "May I ask how uncle is?"],
        keywords: [["how"]], expects: "question",
        hint: "Try: \"How is everyone at home?\"" },
      { npc: "She says she must go now. Say goodbye nicely." },
      { prompt: "End the call politely.",
        expected: ["Goodbye aunty, take care.", "It was nice talking to you. Goodbye.", "Give my love to everyone. Goodbye."],
        keywords: [["goodbye", "bye"]], expects: "state",
        hint: "Try: \"Goodbye aunty, take care.\"" }
    ]
  },

  {
    day: 28, location: "hospital", topic: "Explaining Your Symptoms",
    character: { id: "doctor", name: "Dr. Iyer", role: "doctor" },
    intro: "You are not feeling well. Describe your problem to the doctor clearly.",
    vocabulary: ["I have a", "since", "it hurts when", "I feel", "get better"],
    turns: [
      { npc: "Good morning. Please sit down. What is troubling you?" },
      { prompt: "Describe what is wrong with you.",
        expected: ["I have a bad headache.", "I have a sore throat.", "I have a pain in my stomach."],
        keywords: [["have"]], expects: "state", slot: "symptom",
        hint: "Try: \"I have a bad headache.\"" },
      { npc: "I see. Since when have you had this?" },
      { prompt: "Say how long you have had it.",
        expected: ["Since yesterday morning.", "I have had it for two days.", "Since last night."],
        keywords: [["since", "days", "yesterday", "night"]], expects: "time",
        hint: "Try: \"Since yesterday morning.\"" },
      { npc: "Does anything make it worse?" },
      { prompt: "Say when it gets worse.",
        expected: ["It hurts when I walk.", "It is worse in the morning.", "It hurts when I eat."],
        keywords: [["hurts", "worse"]], expects: "state",
        hint: "Try: \"It hurts when I walk.\"" },
      { npc: "Have you taken any medicine for it?" },
      { prompt: "Say whether you have taken anything.",
        expected: ["No, I have not taken anything.", "Yes, I took a tablet last night.", "No, I did not take any medicine."],
        keywords: [["taken", "took", "medicine"]], expects: "yes_no",
        hint: "Try: \"No, I have not taken anything.\"" },
      { npc: "Do not worry. Rest for two days and you will feel better." },
      { prompt: "Thank the doctor and ask when to come back.",
        expected: ["Thank you. When should I come back?", "Thank you doctor. Should I come again?", "Thank you very much, doctor."],
        keywords: [["thank"]], expects: "state",
        hint: "Try: \"Thank you. When should I come back?\"" }
    ]
  },

  {
    day: 29, location: "transport", topic: "Asking About a Delay",
    character: { id: "conductor", name: "Mr. Das", role: "police" },
    intro: "Your bus is very late. Ask the conductor what has happened.",
    vocabulary: ["how long", "delayed", "another bus", "I am worried", "thank you for telling me"],
    turns: [
      { npc: "I am afraid the bus is running late today." },
      { prompt: "Ask why the bus is late.",
        expected: ["Why is the bus late?", "What has happened to the bus?", "Why is it delayed?"],
        keywords: [["why", "what", "late", "delayed"]], expects: "question",
        hint: "Try: \"Why is the bus late?\"" },
      { npc: "There is heavy traffic near the bridge." },
      { prompt: "Ask how long you will have to wait.",
        expected: ["How long must I wait?", "How long will it take?", "How much longer is the wait?"],
        keywords: [["long"]], expects: "question",
        hint: "Try: \"How long must I wait?\"" },
      { npc: "Perhaps another twenty minutes." },
      { prompt: "Explain that you are worried about being late.",
        expected: ["I am worried because I will be late.", "I am worried, I have to reach school.", "I will be late for school."],
        keywords: [["worried", "late"]], expects: "state",
        hint: "Try: \"I am worried because I will be late.\"" },
      { npc: "I understand. There is another bus from the next street." },
      { prompt: "Ask whether that bus goes to your stop.",
        expected: ["Does that bus go to my stop?", "Will that bus take me there?", "Does it go the same way?"],
        keywords: [["bus", "go", "goes"]], expects: "question",
        hint: "Try: \"Does that bus go to my stop?\"" },
      { npc: "Yes, it does. Hurry and you will catch it." },
      { prompt: "Thank him for telling you.",
        expected: ["Thank you for telling me.", "Thank you very much, sir.", "Thanks a lot for your help."],
        keywords: [["thank", "thanks"]], expects: "state",
        hint: "Try: \"Thank you for telling me.\"" }
    ]
  },

  {
    day: 30, location: "workplace", topic: "A Job Interview",
    character: { id: "manager", name: "Ms. Nair", role: "teacher" },
    intro: "You are being interviewed for a job. Answer the questions confidently.",
    vocabulary: ["tell me about yourself", "my strength", "I have experience", "I am interested in", "look forward"],
    turns: [
      { npc: "Please sit down. Tell me a little about yourself." },
      { prompt: "Introduce yourself in one or two sentences.",
        expected: ["My name is Arjun and I finished school this year.", "I am Arjun. I like working with people.", "My name is Arjun and I am from Delhi."],
        keywords: [["name"]], expects: "name", slot: "name",
        hint: "Try: \"My name is Arjun and I finished school this year.\"" },
      { npc: "Why are you interested in this job?" },
      { prompt: "Explain why you want this job.",
        expected: ["I am interested because I like helping customers.", "Because I want to learn new skills.", "I am interested in this work because it suits me."],
        keywords: [["because", "interested"]], expects: "state",
        hint: "Try: \"I am interested because I like helping customers.\"" },
      { npc: "What would you say is your greatest strength?" },
      { prompt: "Say what you are good at.",
        expected: ["I am good at working in a team.", "My strength is that I work hard.", "I am good at talking to people."],
        keywords: [["good", "strength"]], expects: "state", slot: "strength",
        hint: "Try: \"I am good at working in a team.\"" },
      { npc: "Do you have any experience of this kind of work?" },
      { prompt: "Answer honestly about your experience.",
        expected: ["No, but I learn quickly.", "Yes, I helped in my father's shop.", "I have a little experience from school."],
        keywords: [["learn", "experience", "helped"]], expects: "yes_no",
        hint: "Try: \"No, but I learn quickly.\"" },
      { npc: "Thank you. We will tell you our decision next week." },
      { prompt: "Thank her and say you look forward to hearing from her.",
        expected: ["Thank you. I look forward to hearing from you.", "Thank you for your time.", "Thank you very much for this chance."],
        keywords: [["thank"]], expects: "state",
        hint: "Try: \"Thank you. I look forward to hearing from you.\"" }
    ]
  }
];
