/**
 * Days 11-20: the medium tier.
 *
 * Same ten settings as the easy tier, one step harder: longer answers, a reason
 * or a preference rather than a single fact, and a wider spread of accepted
 * wordings. Every `keywords` entry is drawn from words that actually appear in
 * `expected`, because the evaluator checks a keyword against the best-matching
 * model answer and a keyword that appears nowhere can never be earned.
 */
export default [
  {
    day: 11, location: "school", topic: "Asking the Teacher for Help",
    character: { id: "teacher", name: "Mrs. Sharma", role: "teacher" },
    intro: "You did not understand today's lesson. Ask your teacher for help.",
    vocabulary: ["I did not understand", "could you", "explain", "repeat", "question"],
    turns: [
      { npc: "You look worried. Is everything all right?" },
      { prompt: "Tell the teacher you did not understand the lesson.",
        expected: ["I did not understand the lesson.", "I did not understand today's lesson.", "Sorry, I did not understand it."],
        keywords: [["understand"]], expects: "state",
        hint: "Try: \"I did not understand the lesson.\"" },
      { npc: "That is fine. Which part was difficult?" },
      { prompt: "Say which part was difficult for you.",
        expected: ["The last question was difficult.", "The second part was difficult for me.", "The maths problem was difficult."],
        keywords: [["difficult", "part", "question"]], expects: "state", slot: "topic",
        hint: "Try: \"The last question was difficult.\"" },
      { npc: "Would you like me to explain it again?" },
      { prompt: "Politely ask the teacher to explain it again.",
        expected: ["Yes, could you explain it again please?", "Yes please, could you explain it again?", "Please explain it again."],
        keywords: [["explain"]], expects: "yes_no",
        hint: "Try: \"Yes, could you explain it again please?\"" },
      { npc: "Of course. Come to my desk after the bell." },
      { prompt: "Ask what time you should come.",
        expected: ["What time should I come?", "When should I come?", "At what time shall I come?"],
        keywords: [["time", "when"]], expects: "question",
        hint: "Try: \"What time should I come?\"" },
      { npc: "Come at four o'clock. I will be here." },
      { prompt: "Thank the teacher for helping you.",
        expected: ["Thank you for helping me.", "Thank you very much, teacher.", "Thank you, I will come at four."],
        keywords: [["thank"]], expects: "state",
        hint: "Try: \"Thank you for helping me.\"" }
    ]
  },

  {
    day: 12, location: "park", topic: "Playing a Game Together",
    character: { id: "friend", name: "Ananya", role: "friend" },
    intro: "Your friend is playing in the park. Ask to join the game.",
    vocabulary: ["can I join", "my turn", "let us play", "team", "well played"],
    turns: [
      { npc: "Hi! We are starting a game of cricket. Do you want to play?" },
      { prompt: "Say yes and ask if you can join the game.",
        expected: ["Yes, can I join the game?", "Yes please, can I join?", "Yes, I want to play with you."],
        keywords: [["join", "play"]], expects: "yes_no",
        hint: "Try: \"Yes, can I join the game?\"" },
      { npc: "Great! Which team do you want to be in?" },
      { prompt: "Say which team you want to join.",
        expected: ["I want to be in your team.", "I would like to join your team.", "Your team, please."],
        keywords: [["team"]], expects: "state", slot: "team",
        hint: "Try: \"I want to be in your team.\"" },
      { npc: "You can bat first. Do you know the rules?" },
      { prompt: "Say that you know the rules, or ask her to explain them.",
        expected: ["Yes, I know the rules.", "No, could you explain the rules?", "I know the rules a little."],
        keywords: [["rules"]], expects: "yes_no",
        hint: "Try: \"Yes, I know the rules.\"" },
      { npc: "Good. Be careful of the flowers near the bench!" },
      { prompt: "Promise that you will be careful.",
        expected: ["I will be careful.", "Yes, I will be careful.", "Do not worry, I will be careful."],
        keywords: [["careful"]], expects: "state",
        hint: "Try: \"I will be careful.\"" },
      { npc: "That was a good shot! You play well." },
      { prompt: "Thank your friend and say you enjoyed the game.",
        expected: ["Thank you, I enjoyed the game.", "Thanks, that was fun.", "Thank you, it was a good game."],
        keywords: [["thank", "thanks"]], expects: "state",
        hint: "Try: \"Thank you, I enjoyed the game.\"" }
    ]
  },

  {
    day: 13, location: "shop", topic: "Buying Clothes",
    character: { id: "shopkeeper", name: "Mr. Verma", role: "shopkeeper" },
    intro: "You need a new shirt for school. Talk to the shopkeeper.",
    vocabulary: ["size", "colour", "try it on", "too big", "too small"],
    turns: [
      { npc: "Good morning. How can I help you today?" },
      { prompt: "Say that you are looking for a shirt.",
        expected: ["I am looking for a shirt.", "I want to buy a shirt.", "I need a school shirt."],
        keywords: [["shirt"]], expects: "state",
        hint: "Try: \"I am looking for a shirt.\"" },
      { npc: "We have many shirts. What size do you need?" },
      { prompt: "Tell the shopkeeper your size.",
        expected: ["I need a small size.", "Medium size, please.", "I think I need a large size."],
        keywords: [["size"]], expects: "state", slot: "size",
        hint: "Try: \"I need a medium size.\"" },
      { npc: "Here is a white one and a blue one. Which colour do you like?" },
      { prompt: "Say which colour you prefer.",
        expected: ["I like the blue one.", "I prefer the white one.", "The blue colour, please."],
        keywords: [["blue", "white", "colour"]], expects: "state", slot: "colour",
        hint: "Try: \"I like the blue one.\"" },
      { npc: "Good choice. Would you like to try it on?" },
      { prompt: "Say yes and ask where you can try it.",
        expected: ["Yes, where can I try it?", "Yes please, where is the changing room?", "Yes, I would like to try it on."],
        keywords: [["try"]], expects: "yes_no",
        hint: "Try: \"Yes, where can I try it?\"" },
      { npc: "It fits you well. That will be four hundred rupees." },
      { prompt: "Say you will take it and thank him.",
        expected: ["I will take it, thank you.", "Yes, I will buy it. Thank you.", "I will take this one, thank you."],
        keywords: [["take", "buy"]], expects: "state",
        hint: "Try: \"I will take it, thank you.\"" }
    ]
  },

  {
    day: 14, location: "restaurant", topic: "Ordering for Two",
    character: { id: "waiter", name: "Sanjay", role: "waiter" },
    intro: "You are at a restaurant with your mother. Order food for both of you.",
    vocabulary: ["menu", "for two", "spicy", "water", "the bill"],
    turns: [
      { npc: "Good evening. A table for how many people?" },
      { prompt: "Say that you need a table for two.",
        expected: ["A table for two, please.", "We need a table for two.", "Two people, please."],
        keywords: [["two"]], expects: "number",
        hint: "Try: \"A table for two, please.\"" },
      { npc: "This way, please. Here is the menu. What would you like?" },
      { prompt: "Order some food from the menu.",
        expected: ["I would like rice and dal.", "We would like two plates of rice.", "I want rice, please."],
        keywords: [["like", "want", "rice"]], expects: "state", slot: "food",
        hint: "Try: \"I would like rice and dal.\"" },
      { npc: "Certainly. Would you like it spicy?" },
      { prompt: "Say whether you want it spicy or not.",
        expected: ["Not too spicy, please.", "Yes, a little spicy.", "No, not spicy please."],
        keywords: [["spicy"]], expects: "yes_no",
        hint: "Try: \"Not too spicy, please.\"" },
      { npc: "And anything to drink?" },
      { prompt: "Ask for something to drink.",
        expected: ["Two glasses of water, please.", "Water, please.", "Could we have some water?"],
        keywords: [["water", "drink", "juice"]], expects: "state", slot: "drink",
        hint: "Try: \"Two glasses of water, please.\"" },
      { npc: "I will bring it right away." },
      { prompt: "Ask for the bill politely.",
        expected: ["Could we have the bill, please?", "The bill, please.", "Can I have the bill please?"],
        keywords: [["bill"]], expects: "state",
        hint: "Try: \"Could we have the bill, please?\"" }
    ]
  },

  {
    day: 15, location: "city", topic: "Finding the Post Office",
    character: { id: "stranger", name: "Officer Rao", role: "police" },
    intro: "You need to post a letter. Ask the officer where the post office is.",
    vocabulary: ["excuse me", "how far", "turn left", "straight", "near"],
    turns: [
      { npc: "Yes? Do you need any help?" },
      { prompt: "Politely ask where the post office is.",
        expected: ["Excuse me, where is the post office?", "Could you tell me where the post office is?", "Where is the post office, please?"],
        keywords: [["post", "office"]], expects: "question",
        hint: "Try: \"Excuse me, where is the post office?\"" },
      { npc: "Go straight and take the second left. It is beside the bank." },
      { prompt: "Ask how far it is.",
        expected: ["How far is it?", "Is it far from here?", "How far is the post office?"],
        keywords: [["far"]], expects: "question",
        hint: "Try: \"How far is it?\"" },
      { npc: "About ten minutes on foot." },
      { prompt: "Ask if you can walk there or should take a bus.",
        expected: ["Can I walk there?", "Should I take a bus?", "Is it better to walk or take a bus?"],
        keywords: [["walk", "bus"]], expects: "question",
        hint: "Try: \"Can I walk there?\"" },
      { npc: "You can walk. It is a straight road." },
      { prompt: "Repeat the directions to make sure you understood.",
        expected: ["So I go straight and turn left.", "Straight and then the second left, yes?", "I go straight, then left."],
        keywords: [["straight", "left"]], expects: "state",
        hint: "Try: \"So I go straight and turn left.\"" },
      { npc: "That is right. You will find it easily." },
      { prompt: "Thank the officer for the directions.",
        expected: ["Thank you for your help.", "Thank you very much.", "Thanks a lot, sir."],
        keywords: [["thank", "thanks"]], expects: "state",
        hint: "Try: \"Thank you for your help.\"" }
    ]
  },

  {
    day: 16, location: "home", topic: "Helping at Home",
    character: { id: "mother", name: "Mummy", role: "mother" },
    intro: "Your mother is busy in the kitchen. Offer to help her.",
    vocabulary: ["can I help", "shall I", "wash", "clean", "of course"],
    turns: [
      { npc: "There is so much work today!" },
      { prompt: "Offer to help your mother.",
        expected: ["Can I help you?", "Shall I help you, Mummy?", "Let me help you."],
        keywords: [["help"]], expects: "question",
        hint: "Try: \"Can I help you?\"" },
      { npc: "That is kind of you. Could you clean the table?" },
      { prompt: "Agree to clean the table.",
        expected: ["Yes, I will clean the table.", "Of course, I will clean it.", "Sure, I will do it now."],
        keywords: [["clean", "will"]], expects: "yes_no",
        hint: "Try: \"Yes, I will clean the table.\"" },
      { npc: "Thank you. After that, could you wash the vegetables?" },
      { prompt: "Ask where the vegetables are.",
        expected: ["Where are the vegetables?", "Where can I find the vegetables?", "Where did you keep the vegetables?"],
        keywords: [["where", "vegetables"]], expects: "question",
        hint: "Try: \"Where are the vegetables?\"" },
      { npc: "They are in the basket near the window." },
      { prompt: "Say that you have finished the work.",
        expected: ["I have finished.", "I have finished the work.", "It is done, Mummy."],
        keywords: [["finished", "done"]], expects: "state",
        hint: "Try: \"I have finished the work.\"" },
      { npc: "You are a great help. Thank you, my dear." },
      { prompt: "Say that you were happy to help.",
        expected: ["I am happy to help.", "It was no problem.", "I like helping you."],
        keywords: [["happy", "help", "helping"]], expects: "state",
        hint: "Try: \"I am happy to help.\"" }
    ]
  },

  {
    day: 17, location: "home", topic: "Talking About the Weekend",
    character: { id: "mother", name: "Mummy", role: "mother" },
    intro: "Your mother asks about your weekend plans. Tell her what you want to do.",
    vocabulary: ["weekend", "I want to", "because", "in the morning", "maybe"],
    turns: [
      { npc: "The weekend is coming. What would you like to do?" },
      { prompt: "Say what you would like to do at the weekend.",
        expected: ["I would like to visit the park.", "I want to play with my friends.", "I would like to read a book."],
        keywords: [["want", "would", "like"]], expects: "state", slot: "activity",
        hint: "Try: \"I would like to visit the park.\"" },
      { npc: "That sounds nice. Why do you want to do that?" },
      { prompt: "Give a reason using the word because.",
        expected: ["Because it is fun.", "Because I like it very much.", "Because my friends will be there."],
        keywords: [["because"]], expects: "state",
        hint: "Try: \"Because it is fun.\"" },
      { npc: "All right. Shall we go in the morning or in the evening?" },
      { prompt: "Say which time you prefer.",
        expected: ["In the morning, please.", "I prefer the evening.", "Morning is better for me."],
        keywords: [["morning", "evening"]], expects: "time",
        hint: "Try: \"In the morning, please.\"" },
      { npc: "Good. Who would you like to take with us?" },
      { prompt: "Say who you want to bring.",
        expected: ["I want to take my friend.", "Can my sister come too?", "I would like to bring my brother."],
        keywords: [["friend", "sister", "brother"]], expects: "state", slot: "person",
        hint: "Try: \"I want to take my friend.\"" },
      { npc: "Then it is decided. It will be a lovely weekend." },
      { prompt: "Say that you are excited about it.",
        expected: ["I am very excited.", "I am looking forward to it.", "That is wonderful, thank you."],
        keywords: [["excited", "forward", "wonderful"]], expects: "state",
        hint: "Try: \"I am very excited.\"" }
    ]
  },

  {
    day: 18, location: "hospital", topic: "Getting Medicine",
    character: { id: "doctor", name: "Dr. Iyer", role: "doctor" },
    intro: "The doctor has given you medicine. Ask how to take it.",
    vocabulary: ["medicine", "how many times", "after food", "days", "get well"],
    turns: [
      { npc: "Here is your medicine. Take it carefully." },
      { prompt: "Ask how many times a day you should take it.",
        expected: ["How many times a day should I take it?", "How many times should I take this?", "How often should I take it?"],
        keywords: [["many", "times", "often"]], expects: "question",
        hint: "Try: \"How many times a day should I take it?\"" },
      { npc: "Twice a day, morning and night." },
      { prompt: "Ask whether to take it before or after food.",
        expected: ["Before or after food?", "Should I take it after food?", "Do I take it before food?"],
        keywords: [["food"]], expects: "question",
        hint: "Try: \"Should I take it after food?\"" },
      { npc: "Always after food. Never on an empty stomach." },
      { prompt: "Ask how many days you must take it.",
        expected: ["For how many days?", "How many days should I take it?", "How long do I take it?"],
        keywords: [["days", "long"]], expects: "question",
        hint: "Try: \"For how many days?\"" },
      { npc: "For five days. Come back if you still feel unwell." },
      { prompt: "Say that you understand the instructions.",
        expected: ["I understand.", "Yes, I understand, doctor.", "All right, I understand."],
        keywords: [["understand"]], expects: "state",
        hint: "Try: \"Yes, I understand, doctor.\"" },
      { npc: "Good. Rest well and drink plenty of water." },
      { prompt: "Thank the doctor and say goodbye.",
        expected: ["Thank you, doctor. Goodbye.", "Thank you very much, goodbye.", "Thanks doctor, bye."],
        keywords: [["thank", "thanks"]], expects: "state",
        hint: "Try: \"Thank you, doctor. Goodbye.\"" }
    ]
  },

  {
    day: 19, location: "transport", topic: "Buying a Ticket",
    character: { id: "conductor", name: "Mr. Das", role: "police" },
    intro: "You are travelling to the market. Buy a bus ticket from the conductor.",
    vocabulary: ["one ticket", "how much", "change", "next stop", "get down"],
    turns: [
      { npc: "Tickets, please. Where are you going?" },
      { prompt: "Say where you are going.",
        expected: ["I am going to the market.", "To the market, please.", "I want to go to the market."],
        keywords: [["market", "going"]], expects: "place", slot: "place",
        hint: "Try: \"I am going to the market.\"" },
      { npc: "One ticket to the market. That is fifteen rupees." },
      { prompt: "Give him the money and ask for change.",
        expected: ["Here is twenty rupees.", "Here you are. Can I have the change?", "Here is the money, please give me change."],
        keywords: [["here", "change", "rupees"]], expects: "state",
        hint: "Try: \"Here is twenty rupees.\"" },
      { npc: "Here is your change and your ticket. Keep it safely." },
      { prompt: "Ask how many stops until the market.",
        expected: ["How many stops is it?", "How many stops until the market?", "How many stops from here?"],
        keywords: [["many", "stops"]], expects: "number",
        hint: "Try: \"How many stops is it?\"" },
      { npc: "Four stops. I will tell you when we arrive." },
      { prompt: "Ask him to tell you when to get down.",
        expected: ["Please tell me when to get down.", "Could you tell me when to get down?", "Please let me know when we arrive."],
        keywords: [["tell", "down", "know"]], expects: "state",
        hint: "Try: \"Please tell me when to get down.\"" },
      { npc: "This is your stop. Mind the step as you get down." },
      { prompt: "Thank the conductor and get down.",
        expected: ["Thank you, sir.", "Thank you very much.", "Thanks, goodbye."],
        keywords: [["thank", "thanks"]], expects: "state",
        hint: "Try: \"Thank you, sir.\"" }
    ]
  },

  {
    day: 20, location: "workplace", topic: "Meeting a New Colleague",
    character: { id: "manager", name: "Ms. Nair", role: "teacher" },
    intro: "It is your first day at work. Introduce yourself to the manager.",
    vocabulary: ["nice to meet you", "my first day", "I am from", "I will do my best", "desk"],
    turns: [
      { npc: "Welcome! You must be our new team member." },
      { prompt: "Introduce yourself and say it is your first day.",
        expected: ["Yes, I am Arjun. It is my first day.", "Hello, my name is Arjun. Today is my first day.", "Yes, this is my first day."],
        keywords: [["first", "day"]], expects: "name", slot: "name",
        hint: "Try: \"Yes, I am Arjun. It is my first day.\"" },
      { npc: "Nice to meet you. Where are you from?" },
      { prompt: "Say where you are from.",
        expected: ["I am from Delhi.", "I come from Delhi.", "I am from a small town near Delhi."],
        keywords: [["from"]], expects: "place", slot: "place",
        hint: "Try: \"I am from Delhi.\"" },
      { npc: "Wonderful. Have you worked in an office before?" },
      { prompt: "Answer whether you have worked before.",
        expected: ["No, this is my first job.", "Yes, I worked in an office before.", "No, I have not worked before."],
        keywords: [["job", "worked", "work"]], expects: "yes_no",
        hint: "Try: \"No, this is my first job.\"" },
      { npc: "Do not worry, we will help you learn. Your desk is by the window." },
      { prompt: "Ask what your first task is.",
        expected: ["What should I do first?", "What is my first task?", "What would you like me to do?"],
        keywords: [["first", "task", "do"]], expects: "question",
        hint: "Try: \"What should I do first?\"" },
      { npc: "Read these papers this morning, then we will talk again." },
      { prompt: "Say that you will do your best.",
        expected: ["I will do my best.", "Thank you, I will do my best.", "I will try my best."],
        keywords: [["best"]], expects: "state",
        hint: "Try: \"I will do my best.\"" }
    ]
  }
];
